name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: your-dockerhub-username/saucedemoplaywright:latest
    env:
      ENV: uat

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Playwright tests
      run: npx playwright test --grep '@regressStandAlone'

    - name: Generate Allure Report
      run: npx allure generate report/allure --clean -o report/allure-report

    - name: Upload Allure Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: "allure-report"
        path: "report/allure-report"
        retention-days: 30

    - name: Upload Playwright HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: report/html/
        retention-days: 30

    - name: Upload JUnit Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-report
        path: report/junit/junit.xml
        retention-days: 30